name: CFFormat

on:
  workflow_dispatch:
  repository_dispatch:
    types: [cfformat]
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
    paths: # Only run if *.cfc or github workflows are modified
        - '**.cfc'
        - '.github/workflows/*.yml'
  pull_request:
    branches:
      - development
    paths: # Only run if *.cfc or github workflows are modified
        - '**.cfc'
        - '.github/workflows/*.yml'

jobs:
  # Format PR
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          cmd: run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes