name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - development

jobs:
  tests:
    uses: ./.github/workflows/tests.yml